[package]
name = "rs-doko"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
log = "0.4.22"
rand = "0.9.0-alpha.2"
cli-table = "0.4"
strum = "0.26"
strum_macros = "0.26"
heapless = "0.8.0"
enumset = { version = "1.1.5", features = ["serde"] }