[package]
name = "rs-game-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8.0"
rand = "0.9.0-beta.1"
num-traits = "0.2.19"
serde = { version = "1.0.218", features = ["derive"] }